project:
  type: website
  output-dir: _tmp/projr/v1.0.3/_site
  render:
  - index.qmd
  - save_old_processed.qmd
website:
  title: Processing data for Rodo (2019) TB vaccine candidate comparison paper
  navbar:
    left:
    - href: index.qmd
      text: Home
format:
  html:
    theme: cosmo
    toc: true

